test:
	go test -v digest_test.go


dev:
	go run main.go -mode "dev" -email senna.semakula@gmail.com -level mid -city London -country "United Kingdom" -language javascript
	go run main.go -mode "dev" -email senna.semakula@gmail.com -level mid -city London -country "United Kingdom" -language "python,golang"
	go run main.go -mode "dev" -email senna.semakula@gmail.com -level mid -city London -country "United Kingdom" -language python
	go run main.go -mode "dev" -email senna.semakula@gmail.com -level mid -city London -country "United Kingdom" -language golang
	go run main.go -mode "dev" -email senna.semakula@gmail.com -level mid -city London -country "United Kingdom" -language ruby
	go run main.go -mode "dev" -email senna.semakula@gmail.com -level mid -city London -country "United Kingdom" -language java
	go run main.go -mode "dev" -email senna.semakula@gmail.com -level mid -city London -country "United Kingdom" -language c++
	go run main.go -mode "dev" -email senna.semakula@gmail.com -level mid -city London -country "United Kingdom" -language php

integration:
	go run main.go -mode integration

production:
	go run main.go -mode production

